### PR TITLE
linux: Fix usage xen,force-assign-without-iommu

### PR DESCRIPTION
**Pull request by dsemenets**
xen,force-assign-without-iommu parameter is boolean. Remove value for this parameter

### CODE REVIEW

**Comment by oleksiimoisieiev** [comment]
LGTM `Reviewed-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`
have you tested build with this change?

**Review by lorc — APPROVED** [review]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by dsemenets** [comment]
> LGTM `Reviewed-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>` have you tested build with this change?

Yes.

**Comment by dsemenets** [comment]
Added tags

**Pull request merged**
