### PR TITLE
xen: Use hardcoded commit instead latest.

### PR DESCRIPTION
**Pull request by dsemenets**
Use hardcoded commit instead latest.

### CODE REVIEW

**Review by lorc — COMMENTED** [review]
It would be nice to add *why* we are doing this.

Something like "As this meta-layer can be used by multiple products, it is crucial to fix known working revisions, so depending products can make stable releases based on this meta-layer"

**Comment by dsemenets** [comment]
Updated commit message

**Comment by GrygiriiS** [comment]
`Reviewed-by: Grygorii Strashko <grygorii_strashko@epam.com>`

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by dsemenets** [comment]
Added tags

**Pull request merged**
